### ISSUE TITLE
Remove dataset level errors (use goodtables warnings instead)

### ISSUE THREAD

**Issue by roll** [frictionlessdata/data-quality-spec#11]
# Overview

For now we have a few `dataset` level errors (@pwalsh has named it packaging errors):
- `datapackage-error`
- `jsontableschema-error` (will be moved to table level errors after https://github.com/frictionlessdata/jsontableschema-py/issues/113 will be implemented)

So this `dataset` level errors is only about invalid datapackages. But now we have separate `Resource/TabulalResource` specs so we could have a situation when datapackage is invalid but we still could be able to inspect resources.

Also because of this situation we have to type of errors in goodtables reports - dataset and table level - that's is kinda confusing.

So what I propose:
- move `jsontableschema-error` to table errors (will do anyway)
- remove `datapackage-error` from spec
- all problems found on goodtables presets level (when we extract tables from dataset) add to report as top-level array `report.warnings[]` - it's not only invalid datapackages it could be ckan problems in custom preset or anything so it seems natural to have it as warnings
- instead of providing dataset level errors in GTIO we show warnings about dataset (like there is a wrong datapackage.json prop but we still able to inspect all resources)

---

@pwalsh 
@amercader

**Comment by pwalsh** [comment]
yes: can remove these packaging errors from this spec, which is about data quality, not packaging quality.
