### ISSUE TITLE
Create system for help docs?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/data-quality-spec#5]
@pwalsh wrote:

Users should be able to contribute to creating help docs that correspond with errors we throw in the pipeline.

these docs can be shown on the web via the contextual help in goodtables-web. This has been somewhat stubbed out there.

Actions:
- [ ] Create a new repo for content only (goodtables-handbook, goodtables-help, etc.)
- [ ] Have a markdown docs that corresponds with the ID of each error in goodtables
- [ ] pull the markdown content in as the help content for the errors
- [ ] take this chance to tidy up the report result types a bit - e.g.: use sequential names "schema_001", "structure_014", etc.

**Comment by roll** [comment]
Not sure what's status of this (moving here because not related to goodtables codebase). Also we'got recently big docs contribution.

**Comment by roll** [comment]
@pwalsh 
So is there a new plan how to handle it? Because now it seems more about sending PR to spec.

**Comment by pwalsh** [comment]
just no action at present. we'll see later

**Comment by pwalsh** [comment]
Closing as too old / probably not interesting anymore.
